2024-11-19 16:54:23,171 - __main__ - INFO - 
SESSION: d77dd225-f7a9-4d01-996b-82c3ae73d56c
2024-11-19 16:54:47,173 - __main__ - INFO - 
SESSION: 86f743cd-ee0d-4ca5-a107-dca9a0cf3f7a
2024-11-19 16:55:12,643 - __main__ - INFO - 
SESSION: 4b398979-c54c-498f-a3d4-b201c2285be5
2024-11-19 16:55:13,792 - __main__ - INFO - 
SESSION: 6dc3fee9-6bfc-4daf-a70f-d726ac2fcfde
2024-11-19 16:55:14,003 - __main__ - ERROR - Error loading motion energy for session 6dc3fee9-6bfc-4daf-a70f-d726ac2fcfde: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:55:14,005 - __main__ - INFO - 
SESSION: 76bae405-b169-44ba-95db-b39342f21cf0
2024-11-19 16:55:14,202 - __main__ - ERROR - Error loading motion energy for session 76bae405-b169-44ba-95db-b39342f21cf0: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:55:14,203 - __main__ - INFO - 
SESSION: 90b53484-ed3d-4f62-9dc7-64170e4941ba
2024-11-19 16:55:14,387 - __main__ - ERROR - Error loading motion energy for session 90b53484-ed3d-4f62-9dc7-64170e4941ba: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:55:14,387 - __main__ - INFO - 
SESSION: 50322fbb-5b93-46d7-9ca0-391fa30c966a
2024-11-19 16:55:14,565 - __main__ - ERROR - Error loading motion energy for session 50322fbb-5b93-46d7-9ca0-391fa30c966a: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:55:14,565 - __main__ - INFO - 
SESSION: 731a5f76-c4d6-4485-8584-7adeecdd6f3a
2024-11-19 16:55:18,072 - __main__ - ERROR - Error loading motion energy for session 731a5f76-c4d6-4485-8584-7adeecdd6f3a: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:55:18,072 - __main__ - INFO - 
SESSION: aff40fef-7ef3-4e7a-9451-f248e6d385db
2024-11-19 16:56:10,548 - __main__ - INFO - 
SESSION: 8057374c-baf2-4391-b290-e88743d8981a
2024-11-19 16:56:10,742 - __main__ - ERROR - Error loading motion energy for session 8057374c-baf2-4391-b290-e88743d8981a: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:56:10,742 - __main__ - INFO - 
SESSION: 0bd26d4d-c1c1-4f59-af13-59d19b597ab6
2024-11-19 16:56:11,977 - __main__ - INFO - 
SESSION: 53d8cb2f-3338-4bcd-81c4-6207b660eba3
2024-11-19 16:56:13,203 - __main__ - INFO - 
SESSION: 1cbb24d0-2188-45dc-a116-e23a089c62b4
2024-11-19 16:56:13,407 - __main__ - ERROR - Error loading motion energy for session 1cbb24d0-2188-45dc-a116-e23a089c62b4: 'ROIMotionEnergy'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'ROIMotionEnergy'
2024-11-19 16:56:13,407 - __main__ - INFO - 
SESSION: cbc72b2f-2906-497e-8df0-dfaf825ffb39
2024-11-19 16:56:14,667 - __main__ - INFO - 
SESSION: debe9833-5c26-4d9e-89ba-c63e07e1db10
2024-11-19 16:56:57,835 - __main__ - INFO - 
SESSION: 7149e0fc-a52d-4e93-849c-edc22d54e7a5
2024-11-19 16:56:59,116 - __main__ - INFO - 
SESSION: a7a4a70f-57ae-4586-bb2d-37422deca541
2024-11-19 16:57:00,456 - __main__ - INFO - 
SESSION: 58ca39c5-e27f-43c4-8516-2ccc4fe88042
2024-11-19 16:57:40,060 - __main__ - INFO - 
SESSION: e13d0e58-55c8-4787-a716-03549b3d0240
2024-11-19 16:58:05,645 - __main__ - INFO - 
SESSION: a1d9a3a6-873c-47fe-9350-6c87876a5669
2024-11-19 16:58:33,706 - __main__ - INFO - 
SESSION: a6b9f254-7682-47a4-9abd-753013c87c70
2024-11-19 16:58:53,872 - __main__ - INFO - 
SESSION: 8dfd9963-25e5-4f63-8f91-5b27a5852628
2024-11-19 16:58:57,428 - __main__ - ERROR - Error loading motion energy for session 8dfd9963-25e5-4f63-8f91-5b27a5852628: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:58:57,428 - __main__ - INFO - 
SESSION: 8af06a79-cd95-446e-a57a-7c908d2dbe47
2024-11-19 16:58:58,683 - __main__ - INFO - 
SESSION: 547a8c9a-be6b-4306-8a9a-c154096693ff
2024-11-19 16:59:00,140 - __main__ - INFO - 
SESSION: 2583567d-cd2a-485a-8d79-85aa619e1ce2
2024-11-19 16:59:00,473 - __main__ - ERROR - Error loading motion energy for session 2583567d-cd2a-485a-8d79-85aa619e1ce2: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:59:00,473 - __main__ - INFO - 
SESSION: 996f3585-b804-4a3d-878a-1c15d708962b
2024-11-19 16:59:00,661 - __main__ - ERROR - Error loading motion energy for session 996f3585-b804-4a3d-878a-1c15d708962b: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:59:00,661 - __main__ - INFO - 
SESSION: 98317b26-72d6-4805-9a68-beb7d37f955c
2024-11-19 16:59:00,850 - __main__ - ERROR - Error loading motion energy for session 98317b26-72d6-4805-9a68-beb7d37f955c: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
2024-11-19 16:59:00,850 - __main__ - INFO - 
SESSION: 1bc4aea6-c6fa-4cb8-882f-ea1cc4a12667
2024-11-19 16:59:04,557 - __main__ - ERROR - Error loading motion energy for session 1bc4aea6-c6fa-4cb8-882f-ea1cc4a12667: 'times'
Traceback (most recent call last):
  File "/tmp/ipykernel_794169/2489313231.py", line 11, in <module>
    loader.load_motion_energy()
  File "/home/openlab/anaconda3/envs/iblenv/lib/python3.10/site-packages/brainbox/io/one.py", line 1556, in load_motion_energy
    view, me_raw['times'], me_raw['ROIMotionEnergy'])
KeyError: 'times'
